version: "3.7"

networks:
    laravel:

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx/nginx.Dockerfile
        ports:
            - "${DOCKER_PORT}:80"
        volumes:
            - "./:/app"
        depends_on:
            - php
        networks:
            - laravel

    php:
        volumes:
            - "./:/app"
        build:
            context: .
            dockerfile: docker/php/php.Dockerfile
        container_name: php
        networks:
            - laravel

    cli:
        build:
            context: .
            dockerfile: docker/cli/cli.Dockerfile
        container_name: cli
        volumes:
            - "./:/app"
        networks:
            - laravel

    database:
        container_name: database
        image: mariadb:latest
        volumes:
            - "./docker/database/data:/var/lib/mysql"
        environment:
            MARIADB_DATABASE: laravel
            MARIADB_USER: laravel
            MARIADB_PASSWORD: secret
            MARIADB_ROOT_PASSWORD: secret
        networks:
            - laravel
